### ISSUE TITLE
Importing modules

### ISSUE THREAD

**Issue by bondar-pavel** [aliaksandrb/anydo_api#1]
> from .resource import Resource

I guess it is better to use absolute import path.
So it will look like:

> from anydo_api.resource import Resource

or even import module and use class from it:

> from anydo_api import resource
> resource.Resource(..)

https://github.com/aliaksandrb/anydo_api/blob/master/anydo_api/task.py#L10

**Comment by aliaksandrb** [comment]
Hi @bondar-pavel! I agree, will fix it in a new patches. Thanks! :+1:

**Comment by bondar-pavel** [comment]
wow! nice :+1:
